decada:
  orgId: "o15663558202421"
  appAccessKey: "b6f3a852-4c77-494f-b502-a640b1af7bd4"
  appSecretKey: "b07e29b2-17f1-4220-980d-8690038779af"
  apiUrlV1: "https://portal.decada.gov.sg/enosapi"
  apiUrlV2: "https://ag.decada.gov.sg"
  mqttUrl: "tcp://mqtt.decada.gov.sg:18883"
  productKey: "ucqZBSyF"
  deviceKey: "nn2nF4hWx6"
  deviceSecret: "ZinpXBDF6CFtGNvjk9Tr"
  caFile: "edge_ca.pem"
  keyFile: "edge.key"
  cerFile: "edge.pem"
  keyFilePassword: ""
