decada:
  orgId: "o15663558202421"
  appAccessKey: "b6f3a852-4c77-494f-b502-a640b1af7bd4"
  appSecretKey: "b07e29b2-17f1-4220-980d-8690038779af"
  apiUrlV1: "https://portal.decada.gov.sg/enosapi"
  apiUrlV2: "https://ag.decada.gov.sg"
  mqttUrl: "tcp://mqtt.decada.gov.sg:18883"
  productKey: "Your Product Key"
  deviceKey: "Your Device Key"
  deviceSecret: "Your Device Secret"
  caFile: "The location of your CA pem"
  keyFile: "The location of you Key"
  cerFile: "The location of you Cert"
  keyFilePassword: ""
